CREATE DATABASE PortaleEnteDiFormazione;

USE PortaleEnteDiFormazione;

#TODO: CREAZIONE UTENZE E SUOI DISCENDENTI

CREATE TABLE PROGETTO
(
    Codice CHAR(10) PRIMARY KEY, --SISTEMARE GRANDEZZA
    RER VARCHAR(255) NOT NULL, --SISTEMARE TIPO
    Descrizione VARCHAR(255),
    AnnoInizio INT(4) NOT NULL,
    AnnoFine INT(4) NOT NULL,
    CHECK (AnnoInizio < AnnoFine)
    --CFCoordinatore CHAR(16),
    --FOREIGN KEY (CFCoordinatore) REFERENCES UTENTE(CF)
)

CREATE TABLE MODULO (
    ID INT(5) AUTO_INCREMENT PRIMARY KEY,
    Anno INT(1) NOT NULL,
    Durata INT(3) NOT NULL,
    Descrizione VARCHAR(255),
    CodiceProgetto CHAR(10) NOT NULL,
    FOREIGN KEY (CodiceProgetto) REFERENCES PROGETTO (Codice)
    --CFCoordinatore CHAR(16),
    --FOREIGN KEY (CFCoordinatore) REFERENCES UTENTE(CF)
)

CREATE TABLE CITTA (
    CAP CHAR(5) PRIMARY KEY,
    Nome_Citta VARCHAR(255) NOT NULL,
    Regione_Citta VARCHAR(255) NOT NULL
);

CREATE TABLE SEDE (
    ID INT(5) AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Indirizzo VARCHAR(255) NOT NULL,
    Descrizione VARCHAR(255),
    CAPCitta CHAR(5) NOT NULL,
    FOREIGN KEY (CAPCitta) REFERENCES CITTA (CAP)
);

CREATE TABLE AULA (
    ID INT(5) AUTO_INCREMENT PRIMARY KEY,
    Descrizione VARCHAR(255),
    Capienza INT(3) NOT NULL,
    PresenzaPC BOOLEAN NOT NULL,
    Luogo VARCHAR(255) NOT NULL,
    IDSede INT(5) NOT NULL,
    FOREIGN KEY (IDSede) REFERENCES SEDE (ID)
);

CREATE TABLE LEZIONE (
    ID INT(5) AUTO_INCREMENT PRIMARY KEY,
    Data DATE NOT NULL,
    OraInizio TIME(0) NOT NULL,
    OraFine TIME(0) NOT NULL,
    CHECK (OraInizio < OraFine),
    IDAula INT(5) NOT NULL,
    FOREIGN KEY (IDAula) REFERENCES AULA (ID),
    IDModulo INT(5) NOT NULL,
    FOREIGN KEY (IDModulo) REFERENCES MODULO (ID),
)

CREATE TABLE PRESENZA (
    ID INT(5) AUTO_INCREMENT PRIMARY KEY,
    --CFStudente CHAR(16),
    --FOREIGN KEY (CFStudente) REFERENCES UTENTE (CF),
    IDLezione INT(5) NOT NULL,
    FOREIGN KEY (IDLezione) REFERENCES LEZIONE (ID)
)