CREATE DATABASE IF NOT EXISTS PortaleEnteDiFormazione;

\c PortaleEnteDiFormazione;

CREATE TABLE IF NOT EXISTS UTENTE(
    CF CHAR(16) PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Cognome VARCHAR(255) NOT NULL,
    DataNascita DATE NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Livello INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS DOCENTE(
    CF CHAR(16) PRIMARY KEY REFERENCES UTENTE(CF)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    Telefono CHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROGETTO(
    Codice CHAR(10) PRIMARY KEY,
    RER VARCHAR(255) NOT NULL,
    Descrizione VARCHAR(255),
    AnnoInizio INTEGER NOT NULL,
    AnnoFine INTEGER NOT NULL,
    CHECK (AnnoInizio < AnnoFine),
    CFCoordinatore CHAR(16),
    FOREIGN KEY (CFCoordinatore) REFERENCES DOCENTE(CF)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS STUDENTE(
    CF CHAR(16) PRIMARY KEY REFERENCES UTENTE(CF)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CodiceProgetto CHAR(10),
    FOREIGN KEY (CodiceProgetto) REFERENCES PROGETTO(Codice)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS MODULO (
    ID SERIAL PRIMARY KEY,
    Anno INTEGER NOT NULL,
    OreAula INTEGER NOT NULL,
    OreProject INTEGER DEFAULT 0,
    OreStage INTEGER DEFAULT 0,
    Descrizione VARCHAR(255),
    CodiceProgetto CHAR(10),
    FOREIGN KEY (CodiceProgetto) REFERENCES PROGETTO (Codice)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CFDocente CHAR(16),
    FOREIGN KEY (CFDocente) REFERENCES DOCENTE(CF)
    ON UPDATE CASCADE
    ON DELETE SET NULL
    
);

CREATE TABLE IF NOT EXISTS CITTA (
    CAP CHAR(5) PRIMARY KEY,
    Nome_Citta VARCHAR(255) NOT NULL,
    Regione_Citta VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SEDE (
    ID SERIAL PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Indirizzo VARCHAR(255) NOT NULL,
    Telefono CHAR(10),
    Descrizione VARCHAR(255),
    CAPCitta CHAR(5),
    FOREIGN KEY (CAPCitta) REFERENCES CITTA (CAP)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS AULA (
    ID SERIAL PRIMARY KEY,
    Descrizione VARCHAR(255),
    Capienza INTEGER NOT NULL,
    NumeroPC INTEGER DEFAULT 0,
    Piano VARCHAR(255) NOT NULL,
    Attiva BOOLEAN DEFAULT TRUE,
    IDSede INTEGER,
    FOREIGN KEY (IDSede) REFERENCES SEDE (ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS LEZIONE (
    ID SERIAL PRIMARY KEY,
    Data DATE NOT NULL,
    OraInizio TIME(0) NOT NULL,
    OraFine TIME(0) NOT NULL,
    CHECK (OraInizio < OraFine),
    IDAula INTEGER,
    FOREIGN KEY (IDAula) REFERENCES AULA (ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
    IDModulo INTEGER,
    FOREIGN KEY (IDModulo) REFERENCES MODULO (ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PRESENZA (
    ID SERIAL PRIMARY KEY,
    CFStudente CHAR(16),
    FOREIGN KEY (CFStudente) REFERENCES STUDENTE(CF)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    IDLezione INTEGER,
    FOREIGN KEY (IDLezione) REFERENCES LEZIONE (ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUALIFICA(
    ID SERIAL PRIMARY KEY,
    Materia VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS POSSEDUTO(
    ID SERIAL PRIMARY KEY,
    CFDocente CHAR(16),
    FOREIGN KEY (CFDocente) REFERENCES DOCENTE(CF)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    IDQualifica INTEGER,
    FOREIGN KEY (IDQualifica) REFERENCES QUALIFICA(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);